---
stages:
  - build
  - test
  - deploy

job:
  stage: deploy
  script:
    - rm -rf /opt/dire/germ
    - TEMP="${CI_REPOSITORY_URL#*@}"
    - CI_PROJECT_SSH_URL=${TEMP%%/*}
    - git clone git@"${CI_PROJECT_SSH_URL}":dire/${CI_PROJECT_NAME}.git /opt/dire/germ
    - cd /opt/dire/germ
    - git checkout "${CI_BUILD_REF}"
    - bash /opt/dire/germ/tools/operate.sh
  except:
    - tags
  image: dire/deploy
  tags:
    - dire

variables:
  GIT_STRATEGY: none