---
stages:
  - print

job:
  stage: print
  script:
    - ls
  before_script:
    - echo "172.28.0.4  deploy.mydomain.com" >> /etc/hosts
    - mkdir -p /builds/dire/germ
  tags: 
  except:
    - tags
  image: dire/ansible_tools:latest

variables:
  GIT_STRATEGY: none
