# for deploy

deploy_ip: '10.0.35.21'
cluster_domain: mydomain.com
docker_registry: "{{deploy_host}}"
deploy_host: 'deploy.{{cluster_domain}}'
external_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

name_servers:
  - 114.114.114.114

reset_network_force: true

## Change this to use another Kubernetes version, e.g. a current beta release
#kube_version: v1.9.5
kube_version: v1.11.1

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18

# internal network node size allocation (optional). This is the size allocated
# to each node on your network.  With these defaults you should have
# room for 4096 nodes with 254 pods per node.
kube_network_node_prefix: 24

# Can be ipvs, iptables
kube_proxy_mode: iptables

# DNS configuration.
# Kubernetes cluster name, also will be used as DNS domain
cluster_name: cluster.local
# Can be dnsmasq_kubedns, kubedns, coredns, coredns_dual, manual or none
dns_mode: coredns
# Set manual server if using a custom cluster DNS server
#manual_dns_server: 10.x.x.x
#
download_run_once: false

external_nameservers:
  - "114.114.114.114"

# Helm deployment
helm_enabled: true
helm_stable_repo_url: "http://{{ deploy_host }}/repository/helm/"
helm_version: "v2.9.1"

kubelet_authentication_token_webhook: true

germ_path: '/opt/dire/k8s-test/germ'


work_space: '/opt/dire'
steam_path: '{{work_space}}/steam'
kubespray_path: '{{work_space}}/kubespray'

