## GitLab CE image
image: deploy.domymain.com/k8s/gitlab-ce:9.4.1-ce.0

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
imagePullPolicy: IfNotPresent

## The URL (with protocol) that your users will use to reach the install.
externalUrl: http://deploy.gitlab.com/

## Change the initial default admin password if set. If not set, you'll be
## able to set it when you first visit your install.
gitlabRootPassword: "abc123456"

## For minikube, set this to NodePort, elsewhere use LoadBalancer
serviceType: LoadBalancer

## Ingress configuration options
##cd g
ingress:
  annotations:
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  enabled: false
  tls:
  # - secretName: gitlab.cluster.local
  #   hosts:
  #     - gitlab.cluster.local
  url: gitlab.cluster.local

## Configure external service ports
sshPort: 22
httpPort: 80
httpsPort: 443
## livenessPort Port of liveness probe endpoint
livenessPort: http
## readinessPort Port of readiness probe endpoint
readinessPort: http


## Configure resource requests and limits
resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1

## Enable persistence using Persistent Volume Claims
persistence:
  ## This volume persists generated configuration files, keys, and certs.
  ##
  gitlabEtc:
    enabled: true
    size: 1Gi

    accessMode: ReadWriteOnce

postgresql:
  image: "deploy.domymain.com/k8s/postgres"
  imageTag: "9.6.2"
  cpu: 1000m
  memory: 1Gi

  postgresUser: gitlab
  postgresPassword: gitlab
  postgresDatabase: gitlab

  persistence:
    size: 10Gi

redis:
  image: deploy.domymain.com/k8s/redis:3.2.9-r2
  redisPassword: "gitlab"

  resources:
    requests:
      memory: 1Gi

  persistence:
    size: 10Gi