---
- name: include options
  hosts:
    - all
  tags: always
  become: true
  tasks:
    - include_vars: ../etc/globals.yml
    - include_vars: ../etc/germ.yml


- name: import prometheus-deploy playbook
  import_playbook: deploy.yml