---
- name: include steam playbook
  import_playbook: ../../site.yml

- name: include options
  hosts:
    - all
  tags: always
  become: true
  tasks:
    - include_vars: ../etc/globals.yml
    - include_vars: ../etc/germ.yml

- name: import kubelet install playbook
  import_playbook: install.yml
