---
- name: include options
  hosts:
    - all
    - localhost
  tags: always
  tasks:
    - include_vars: '{{ item }}'
      with_items:
        - '../../etc/germ/passwords.yml'

- name: include options
  hosts:
    - all
    - localhost
  tags: always
  become: true
  tasks:
    - include_vars: etc/globals.yml

- import_playbook: '{{satellite_path}}/ansible/site.yml'
