---
- name: include options
  hosts:
    - all
  tags: always
  become: true
  tasks:
    - include_vars: etc/globals.yml

#- import_playbook: pre-play.yml

#- import_playbook: /home/kolla/dire/kolla-ansible/ansible/site.yml

- import_playbook: post-play.yml
  tags: post-play
