---
- name: deploy cloud os
  import_playbook: ../site.yml

- name: include options
  hosts:
    - all
    - localhost
  tags: always
  become: true
  tasks:
    - include_vars: etc/globals.yml

- import_playbook: '{{kolla_path}}/ansible/site.yml'

#- import_playbook: post-play.yml
#  tags: post-play
