---
- name: include options
  hosts:
    - all
    - localhost
  tags: always
  gather_facts: false
  tasks:
    - include_vars: '{{ item }}'
      with_items:
        - '../etc/germ/passwords.yml'

- name: run init play book
  import_playbook: '{{steam_path}}/ansible/site.yml'

- name: include options
  hosts:
    - all
  tags: always
  tasks:
    - include_vars: '{{ item }}'
      with_items:
        - '../etc/germ/auth.yml'
