---
- name: include options
  hosts:
    - all
  tags: always
  tasks:
    - include_vars: '{{ item }}'
      with_items:
        - '../etc/kolla/passwords.yml'
        - '../etc/kolla/globals.yml'

- name: run init play book
  import_playbook: /home/kolla/dire/steam/ansible/site.yml

- name: include options
  hosts:
    - all
  tags: always
  become: true
  tasks:
    - include_vars: '{{ item }}'
      with_items:
        - '../etc/kolla/auth.yml'

- name: run test
  import_playbook: openstack/site.yml
  when: cluster_type == 'openstack'
