---
- name: genrate private key file
  hosts: localhost
  vars_files:
    - '{{germ_path}}/etc/germ/passwords.yml'
  gather_facts: no
  tasks:
    - blockinfile:
        path: '{{germ_path}}/etc/germ/id_rsa'
        content: '{{kolla_ssh_key.private_key }}'
        mode: 0600
        create: True
